services:
    thunder.custommenu.listener:
        class: thunder\custommenu\event\main_listener
        arguments:
            - '@config'
            - '@config_text'
            - '@template'
            - '@user'
            - '@auth'
        tags:
            - { name: event.listener }
